project:
  type: default

format:
  beamer:
    aspectratio: 169
    include-in-header: beamer_template.tex
    slide-level: 2

author: "Raul Riva"
institute: "FGV EPGE"
date: "2026-01-01"
date-format: "MMMM, YYYY"
jupyter: python3
highlight-style: github
urlcolor: FGVBlue
citecolor: FGVBlue
linkcolor: FGVBlue
link-citations: true
